CREATE TABLE [dbo].[customer]
(
	[cust_id] [int] NULL,
	[name] [nvarchar](MAX) NULL,
	[cust_type] [tinyint] NULL,
	[company_type] [tinyint] NULL,
	[reg_code] [varchar](MAX) NULL,
	[vat_code] [varchar](MAX) NULL,
	[cust_ref_no] [varchar](MAX) NULL,
	[lang] [int] NULL,
	[address_id] [int] NULL,
	[address_street] [nvarchar](MAX) NULL,
	[address_city] [nvarchar](MAX) NULL,
	[address_country] [nvarchar](MAX) NULL,
	[address_post_code] [nvarchar](MAX) NULL,
	[address_name] [nvarchar](MAX) NULL,
	[phone] [varchar](MAX) NULL,
	[fax] [varchar](MAX) NULL,
	[email] [nvarchar](MAX) NULL,
	[branch_id] [int] NULL,
	[cust_group_id] [int] NULL,
	[description] [nvarchar](MAX) NULL,
	[web_username] [varchar](MAX) NULL,
	[web_psw] [nvarchar](MAX) NULL,
	[insurance_dt] [datetime] NULL,
	[insurance_amount] [int] NULL,
	[decision_dt] [datetime] NULL,
	[decision_no] [nvarchar](MAX) NULL,
	[decision_type] [int] NULL,
	[guarantee_type] [int] NULL,
	[guarantee_bank] [nvarchar](MAX) NULL,
	[guarantee_amount] [int] NULL,
	[guarantee_amount_str] varchar(100) null,
	[guarantee_valid_from] [datetime] NULL,
	[guarantee_valid_to] [datetime] NULL,
	[guarantee_description] [nvarchar](MAX) NULL,
	[ins_decision_date] [datetime] NULL,
	[insf_evaluated_dt] [datetime] NULL,
	[insf_limit_amount] [int] NULL,
	[insf_risk_class] [int] NULL,
	[insf_monitoring] [int] NULL,
	[insf_last_mon_dt] [datetime] NULL,
	[insf_next_mon_dt] [datetime] NULL,
	[mng_name] [nvarchar](MAX) NULL,
	[mng_position] [nvarchar](MAX) NULL,
	[mng_phone] [nvarchar](MAX) NULL,
	[mng_email] [nvarchar](MAX) NULL,
	[mng_description] [nvarchar](MAX) NULL,
	[send_advertise] [bit] NULL,
)


CREATE TABLE [dbo].[contract]
(
	[cust_id] [int] NULL,
	[contract_id] [int] NULL,
	[contract_type] [tinyint] NULL,
	[contract_name] [nvarchar](MAX) NULL,
	[address1_id] [int] NULL,
	[address1_street] [nvarchar](MAX) NULL,
	[address1_city] [nvarchar](MAX) NULL,
	[address1_country] [nvarchar](MAX) NULL,
	[address1_post_code] [nvarchar](MAX) NULL,
	[Address1_name] [nvarchar](MAX) NULL,
	[address2_id] [int] NULL,
	[address2_street] [nvarchar](MAX) NULL,
	[address2_city] [nvarchar](MAX) NULL,
	[address2_country] [nvarchar](MAX) NULL,
	[address2_post_code] [nvarchar](MAX) NULL,
	[address2_name] [nvarchar](MAX) NULL,
	[phone] [varchar](MAX) NULL,
	[fax] [varchar](MAX) NULL,
	[email] [nvarchar](MAX) NULL,
	[parent_id] [int] NULL,
	[ext_nav_code] [nvarchar](MAX) NULL,
	[contract_no] [nvarchar](MAX) NULL,
	[fin_type] [int] NULL,
	[valid_from] [datetime] NULL,
	[valid_to] [datetime] NULL,
	[lang] [int] NULL,
	[agent_id] [int] NULL,
	[state] [smallint] NULL,
	[curr] [char](3) NULL,
	[curr_rate_provider_id] [int] NULL,
	[inv_freq] [smallint] NULL,
	[inv_series_id] [int] NULL,
	[inv_template_id] [int] NULL,
	[send_inv] [bit] NULL,
	[inv_show_dt] [bit] NULL,
	[cred_dt_from] [datetime] NULL,
	[max_debt_block] [bigint] NULL,
	[max_debt_disc] [bigint] NULL,
	[pay_term] [smallint] NULL,
	[cred_term] [smallint] NULL,
	[pay_delay] [smallint] NULL,
	[fine] [smallmoney] NULL,
	[disc_check_pay] [bit] NULL,
	[disc_curr_period] [bit] NULL,
	[disc_foreign] [bit] NULL,
	[transfer_auto] [bit] NULL,
	[mng_name] [nvarchar](MAX) NULL,
	[mng_position] [nvarchar](MAX) NULL,
	[mng_phone] [nvarchar](MAX) NULL,
	[mng_email] [nvarchar](MAX) NULL,
	[mng_description] [nvarchar](MAX) NULL,
	[description] [nvarchar](MAX) NULL,
	[block_reason] [nvarchar](MAX) NULL,
	[contract_group_id] [int] NULL,
	[inv_send_email] [bit] NULL,
	[data_temp_changed] [bit] NULL,
	[inv_comment_id] [int] NULL,
	[agg_fuel_quantity] [bigint] NULL,
	[agg_penalty_type] [tinyint] NULL,
	[send_advertise] [bit] NULL,
	[dd_agreement_no] [nvarchar](MAX) NULL,
	[credit_limit] [bigint] NULL,
	[campaign_code] [varchar](MAX) NULL,
	[einvoice_address] [varchar](MAX) NULL,
	[sales_person] [nvarchar](MAX) NULL,
)

CREATE TABLE [dbo].[iban]
(
	[contract_id] [int] NULL,
	[type] [int] NULL,
	[acc_number] [varchar](MAX) NULL,
	[bank_code] [varchar](MAX) NULL,
	[direct_debit] [Bit] NULL,
	[direct_debit_no] [varchar](MAX) NULL,
)

CREATE TABLE [dbo].[bank_transfer]
(
	[contract_id] [int] NULL,
	[cust_id] [int] NULL,
	[file_name] [varchar](MAX) NULL,
	[transfer_no] [nvarchar](MAX) NULL,
	[transfer_line_no] [varchar](MAX) NULL,
	[payer_name] [nvarchar](MAX) NULL,
	[cust_iban] [varchar](MAX) NULL,
	[payer_no] [varchar](MAX) NULL,
	[primary_payer_no] [varchar](MAX) NULL,
	[primary_payer_name] [nvarchar](MAX) NULL,
	[recipient_iban] [varchar](MAX) NULL,
	[transfer_amount] [bigint] NULL,
	[transfer_dt] [datetime] NULL,
	[transfer_comment] [nvarchar](MAX) NULL,
	[netting] [bit] NULL,
)

CREATE TABLE [dbo].[terminal]
(
	[ca_id] [nvarchar](MAX) NULL,
	[terminal_id] [nvarchar](MAX) NULL,
	[frame_no] [nvarchar](MAX) NULL,
	[state] [tinyint] NULL,
)

CREATE TABLE [dbo].[item]
(
	[acq_code] [varchar](MAX) NULL,
	[item_group] [tinyint] NULL,
	[item_code] [varchar](MAX) NULL,
	[item_name] [nvarchar](MAX) NULL,
	[vat_rate] numeric(10,4),
	[excise] numeric(10,4),
	[stockpile_fee] numeric(10,4),
)

CREATE TABLE [dbo].[document]
(
	[contract_id] [int] NULL,
	[cust_id] [int] NULL,
	[dt_from] [datetime] NULL,
	[dt_to] [datetime] NULL,
	[inv_dt] [datetime] NULL,
	[pay_dt] [datetime] NULL,
	[amount] [money] NULL,
	[amount_wo_vat] [money] NULL,
	[paid_dt] [datetime] NULL,
	[paid_amount] [money] NULL,
	[paid] [bit] NULL,
	[inv_no] [int] NULL,
	[inv_series] [nvarchar](MAX) NULL,
	[files] [nvarchar](MAX) NULL,
	[doc_type] [int] NULL,
	[ext_ref_no] [varchar](MAX) NULL,
	[inv_no_str] varchar(MAX) NULL,
)

CREATE TABLE [dbo].[supplier_price]
(
	[supplier] [nvarchar](MAX) NULL,
	[product] [varchar](MAX) NULL,
	[dt] [datetime] NULL,
	[price] [numeric](12,5) NULL,
)

CREATE TABLE [dbo].[card]
(
	[contract_id] [int] NULL,
	[cust_id] [int] NULL,
	[card_no] [varchar](MAX) NULL,
	[state_block] [smallint] NULL,
	[state_stolen] [smallint] NULL,
	[state_lost] [smallint] NULL,
	[check_days] [tinyint] NULL,
	[month_limit1] [bigint] NULL,
	[month_limit2] [bigint] NULL,
	[month_limit3] [bigint] NULL,
	[week_limit1] [bigint] NULL,
	[week_limit2] [bigint] NULL,
	[week_limit3] [bigint] NULL,
	[day_limit1] [bigint] NULL,
	[day_limit2] [bigint] NULL,
	[day_limit3] [bigint] NULL,
	[valid_from] [datetime] NULL,
	[valid_to] [datetime] NULL,
	[is_local] [tinyint] NULL,
	[branch_id] [int] NULL,
	[description] [nvarchar](MAX) NULL,
	[block_description] [nvarchar](MAX) NULL,
	[prod_pin_block] [nvarchar](MAX) NULL,
	[prod_pin_encrypted] [nvarchar](MAX) NULL,
	[prod_track1] [nvarchar](MAX) NULL,
	[prod_track2] [nvarchar](MAX) NULL,
	[prod_embos1] [nvarchar](MAX) NULL,
	[prod_embos2] [nvarchar](MAX) NULL,
	[prod_embos3] [nvarchar](MAX) NULL,
	[prod_embos4] [nvarchar](MAX) NULL,
	[rg_id] [int] NULL,
	[address_id] [int] NULL,
	[address_street] [nvarchar](MAX) NULL,
	[address_city] [nvarchar](MAX) NULL,
	[address_country] [nvarchar](MAX) NULL,
	[address_post_code] [nvarchar](MAX) NULL,
	[address1_name] [nvarchar](MAX) NULL,
	[ask_odometer] [bit] NULL,
	[ask_vrn] [bit] NULL,
)

CREATE TABLE [dbo].[card_acceptor]
(
	[ca_id] [nvarchar](MAX) NULL,
	[acq_inst] [varchar](MAX) NULL,
	[brand_inst] [varchar](MAX) NULL,
	[ca_name] [nvarchar](MAX) NULL,
	[ca_address] [varchar](MAX) NULL,
	[ca_city] [varchar](MAX) NULL,
	[ca_country] [char](3) NULL,
	[ca_phone] [nvarchar](MAX) NULL,
	[ca_email] [varchar](MAX) NULL,
	[state] [tinyint] NULL,
	[ca_disc] [bit] NULL,
	[municipality_id] [char](4) NULL,
	[ca_type] [char](1) NULL,
)

CREATE TABLE [dbo].[transaction]
(
	[tran_id] [bigint] NULL,
	[tran_det_id] [bigint] NULL,
	[contract_id] [int] NULL,
	[inv_id] [int] NULL,
	[auth_code] [varchar](MAX) NULL,
	[rcpt_no] [varchar](MAX) NULL,
	[card_no] [varchar](MAX) NULL,
	[acq_inst] [varchar](MAX) NULL,
	[ca_id] [varchar](MAX) NULL,
	[term_id] [varchar](MAX) NULL,
	[loc_dt] [datetime] NULL,
	[sys_dt] [datetime] NULL,
	[curr_loc] [varchar](MAX) NULL,
	[curr_rate] [numeric](18,10) NULL,
	[amount_loc_r] [int] NULL,
	[amount_loc_vat_r] [int] NULL,
	[amount_loc_excise_r] [int] NULL,
	[amount_sys_r] [int] NULL,
	[odometer] [varchar](MAX) NULL,
	[vrn] [varchar](MAX) NULL,
	[comment] [nvarchar](MAX) NULL,
	[item_group] [tinyint] NULL,
	[product_group] [varchar](MAX) NULL,
	[item_code] [varchar](MAX) NULL,
	[item_name] [nvarchar](MAX) NULL,
	[item_um] [varchar](MAX) NULL,
	[item_quantity] [money] NULL,
	[item_price] [money] NULL,
	[amount_loc_rd] [int] NULL,
	[amount_loc_vat_rd] [int] NULL,
	[amount_sys_rd] [int] NULL,
	[vat_rate] [smallmoney] NULL,
	[amount_loc_excise_rd] [int] NULL,
)
CREATE TABLE [dbo].[contract_balance]
(
	[contract_id] [int] NULL,
	[cust_id] [int] NULL,
	[amount] [bigint] NULL,
	[dt] [datetime] NULL,
)

CREATE TABLE [dbo].[discount_row]
(
	[contract_id] [int] NULL,
	[item_group] [tinyint] NULL,
	[product_group] [varchar](MAX) NULL,
	[ca_id] [int] NULL,
	[ca_group_id] [int] NULL,
	[price_model] [int] NULL,
	[disc_type] [varchar](MAX) NULL,
	[disc0] [decimal](19, 6) NULL,
	[priority] [int] NULL,
	[bound_type] [tinyint] NULL,
	[bound1] [bigint] NULL,
	[disc1] [decimal](19, 6) NULL,
	[bound2] [bigint] NULL,
	[disc2] [decimal](19, 6) NULL,
	[bound3] [bigint] NULL,
	[disc3] [decimal](19, 6) NULL,
	[bound4] [bigint] NULL,
	[disc4] [decimal](19, 6) NULL,
	[bound5] [bigint] NULL,
	[disc5] [decimal](19, 6) NULL,
	[bound6] [bigint] NULL,
	[disc6] [decimal](19, 6) NULL,
	[bound7] [bigint] NULL,
	[disc7] [decimal](19, 6) NULL,
	[bound8] [bigint] NULL,
	[disc8] [decimal](19, 6) NULL,
	[bound9] [bigint] NULL,
	[disc9] [decimal](19, 6) NULL,
	[bound10] [bigint] NULL,
	[disc10] [decimal](19, 6) NULL,
)














